### ISSUE TITLE
Template Duplication: Failure `sourceCodeToTemplateId` not unique!

### ISSUE THREAD

**Issue by meck93** [alexzaganelli/strapi-plugin-email-designer#60]
## Bug Description 
During the introduction of the new variable `sourceCodeToTemplateId` I forgot to test and update the duplicate functionality. 
Currently, it no longer works as the `sourceCodeToTemplateId` is just copied and not removed. 

### Error Message

```bash
POST /email-designer/templates/duplicate/6 (106 ms) 500
warn Duplicate entry error: insert into "email_templates" ("bodyHtml", "bodyText", "created_at", "design", "enabled", "name", "sourceCodeToTemplateId", "subject", "tags", "updated_at") values ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10) returning * - duplicate key value violates unique constraint "email_templates_sourceCodeToTemplateId_unique"
error Error: Duplicate entry 
    at handleDatabaseError (/node_modules/strapi-connector-bookshelf/lib/utils/errors.js:25:11)
    at Object.create (/node_modules/strapi-connector-bookshelf/lib/queries.js:60:14)
    at processTicksAndRejections (node:internal/process/task_queues:94:5)
```

**Comment by meck93** [comment]
@alexzaganelli can you build a new release to publish the latest version with the bugfix? thanks!
