### ISSUE TITLE
[Strapi V4] 😔 templates got deleted out of nowhere

### ISSUE THREAD

**Issue by Flowko** [alexzaganelli/strapi-plugin-email-designer#85]
damn, well thats a weird one.

all the templates i created are gone, the last trace of what happened :
ive checked before it, nothing was out of the ordinary, all requests were 200
```
[2022-02-13 00:06:00.882] error: select "t0".* from "email_templates" as "t0" - relation "email_templates" does not exist
error: select "t0".* from "email_templates" as "t0" - relation "email_templates" does not exist
    at Parser.parseErrorMessage ([Project-folder]\node_modules\pg-protocol\dist\parser.js:287:98)
    at Parser.handlePacket ([Project-folder]\node_modules\pg-protocol\dist\parser.js:126:29)     
    at Parser.parse ([Project-folder]\node_modules\pg-protocol\dist\parser.js:39:38)
    at TLSSocket.<anonymous> ([Project-folder]\node_modules\pg-protocol\dist\index.js:11:42)     
    at TLSSocket.emit (node:events:390:28)
    at TLSSocket.emit (node:domain:475:12)
    at addChunk (node:internal/streams/readable:315:12)
    at readableAddChunk (node:internal/streams/readable:289:9)
    at TLSSocket.Readable.push (node:internal/streams/readable:228:10)
    at TLSWrap.onStreamRead (node:internal/stream_base_commons:199:23)
[2022-02-13 00:06:10.894] http: GET /admin/plugins/email-designer (2 ms) 200
[2022-02-13 00:06:10.913] http: GET /admin/runtime~main.2229d96d.js (2 ms) 200
[2022-02-13 00:06:10.916] http: GET /admin/main.39ff1a78.js (1 ms) 200
[2022-02-13 00:06:11.095] http: GET /admin/project-type (2 ms) 200
```

im using postgresql as the db, its hosted on heroku

**Comment by alexzaganelli** [comment]
What's was your last action? Honestly I don't think it's could be related to this plug-in. There is only one `.delete` command and the `.update` ones couldn't erase nothing.

**Comment by Flowko** [comment]
yeah it might've been something related to the db im using or how its configured, i noticed something a bit weird, that it doesnt save some changes, so when i try to rerun strapi again some changes are not even there anymore, ill close this for now,
#alwaysHitExport :)

**Comment by lkjimy** [comment]
Had the same happen in my project, using MySQL here. Spent a long time getting things ready for this to happen for no apparent reason.
