### ISSUE TITLE
Strapi 4.0.8: Could not load js config file node_modules\strapi-plugin-email-designer\strapi-server.js

### ISSUE THREAD

**Issue by chudno** [alexzaganelli/strapi-plugin-email-designer#88]
Cant't start dev server after plugin installation:

Building your admin UI with development configuration 
i Compiling Webpack
√ Webpack: Compiled successfully in 10.90s
Admin UI built successfully
[2022-02-17 15:08:23.951] debug: ⛔️ Server wasn't able to start properly.
**[2022-02-17 15:08:23.953] error: Could not load js config file .\node_modules\strapi-plugin-email-designer\strapi-server.js: Unexpected token '?'
Error: Could not load js config file .\node_modules\strapi-plugin-email-designer\strapi-server.js: Unexpected token '?'**
    at loadJsFile (.\node_modules\@strapi\strapi\lib\core\app-configuration\load-config-file.js:18:11)
    at loadFile (.\node_modules\@strapi\strapi\lib\core\app-configuration\load-config-file.js:35:14)
    at Object.loadPlugins (.\node_modules\@strapi\strapi\lib\core\loaders\plugins\index.js:96:26)
    at async Strapi.loadPlugins (.\node_modules\@strapi\strapi\lib\Strapi.js:277:5)
    at async Promise.all (index 1)
    at async Strapi.register (.\node_modules\@strapi\strapi\lib\Strapi.js:309:5)
    at async Strapi.load (.\node_modules\@strapi\strapi\lib\Strapi.js:407:5)
    at async Strapi.start (.\node_modules\@strapi\strapi\lib\Strapi.js:161:9)

**Comment by NickVishwamitraJTY** [comment]
Recieving this error too. Had to uninstall this plugin as I couldn't figure it out

**Comment by alexzaganelli** [comment]
Hi guys, 

the '?' is the optional chaining operator introduced in @babel/preset-env, in ES2020.

Take a look [here](https://babeljs.io/docs/en/babel-plugin-proposal-optional-chaining)
